openapi: 3.0.0
info:
  description: |
    Credentialing is the verification process that GoodHire follows to ensure companies requesting reports are legitimate.
  version: 1.0.0
  title: Credentialing API 2
tags:
  - name: Credentialing
    description: Everything about Credentialing
paths:
  /applications:
    post:
      summary: Starts credentialing process
      operationId: create-application
      responses:
        '201':
          description: Created
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/ApplicationRequest'
      tags:
        - Applications
    parameters: []
    get:
      summary: Get applications
      operationId: get-applications
      responses:
        '200':
          description: OK
      description: ''
      parameters:
        - schema:
            type: string
          in: query
          name: organizationId
      tags:
        - Applications
  '/applications/{id}':
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the credentialing
      summary: Get application
      operationId: get-application-by-id
      responses:
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Credentialing not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: ''
      tags:
        - Applications
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/applications/{id}/status':
    post:
      summary: Change the application status
      operationId: change-application-status
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: application not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/HoldRequest'
        content:
          application/json:
            schema:
              type: object
              properties:
                Status:
                  type: string
                Notes:
                  type: string
      description: ''
      tags:
        - Applications
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: ''
      operationId: get-applications-id-status
      responses:
        '200':
          description: OK
      tags:
        - Applications
  /verification-result:
    put:
      summary: Updates company application info
      operationId: update
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: application not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/CompanyInfoRequest'
      description: ''
      tags:
        - Verification results
    parameters: []
    get:
      summary: Get result of the credentialing for specific application
      operationId: get-verification-result
      responses:
        '200':
          description: OK
      description: ''
      tags:
        - Verification results
  '/documents/{id}':
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the document
      summary: Get document
      operationId: get-document-by-id
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Credit Credentialing not found
      tags:
        - Documents
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: Remove document
      operationId: delete-documents-id
      responses:
        '200':
          description: OK
    put:
      summary: Replace document
      operationId: put-documents-id
      responses:
        '200':
          description: OK
      description: ''
  /questionnaires:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the credit credentialing
      summary: Adds the credit credentialing questionnaire
      operationId: addCreditCredentialinQquestionnaire
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Credit Credentialing not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/QuestionnaireRequest'
      tags:
        - Credit verification supporting steps
    parameters: []
  /inspection:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the credit credentialing
      summary: Adds Credit Credentialing Onsite Inspection Info
      operationId: addOnSiteInspection
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Credit Credentialing not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/InspectionRequest'
      tags:
        - Credit verification supporting steps
  /exemption:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the credit credentialing
      summary: Adds On-site inspection exemption to credit credentialing
      operationId: addOnSiteInspectionExemption
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Credit Credentialing not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/ExemptionRequest'
      tags:
        - Credit verification supporting steps
  /payment:
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the credit credentialing
      summary: Marks that user paid for On-site inspection
      operationId: markAsPaid
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Credit Credentialing not found
        '405':
          description: Validation exception
      requestBody:
        $ref: '#/components/requestBodies/PaymentRequest'
      tags:
        - Credit verification supporting steps
  /documents:
    parameters: []
    post:
      summary: Upload document
      operationId: post-documents
      responses:
        '200':
          description: OK
      tags:
        - Documents
    get:
      summary: Get documents
      operationId: get-documents
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
          in: query
          name: applicationId
        - schema:
            type: string
          in: query
          name: type
      tags:
        - Documents
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  requestBodies:
    UserInfoRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserRequest'
      description: User Info
      required: true
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/UserInfo'
      description: List of user object
      required: true
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:all': modify everything
            'read:all': read everything
    api_key:
      type: apiKey
      name: api_key
      in: header
